name: tailnet-proxy

services:
  caddy:
    build: .
    restart: unless-stopped
    environment:
      - UPSTREAM=${UPSTREAM}
    volumes:
      - config:/config
      - data:/data
    network_mode: service:tailscale

  tailscale:
    image: tailscale/tailscale
    restart: unless-stopped
    hostname: tailnet-proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - TS_ACCEPT_DNS=true
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun
    cap_add:
      - net_admin

volumes:
  config:
  data:
  tailscale:
